# Generated by Django 3.2.3 on 2025-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20250709_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shortcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Короткий код'),
        ),
        migrations.DeleteModel(
            name='ShortCodeRecipe',
        ),
    ]
