# Generated by Django 3.2.3 on 2025-07-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='shortcode',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Короткий код'),
        ),
    ]
